"""Add auto_reply preferences

Revision ID: 38ef62fcfd6b
Revises: 
Create Date: 2025-04-05 03:55:50.525943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ef62fcfd6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_reply_tone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('auto_reply_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('auto_reply_signature', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.drop_column('auto_reply_signature')
        batch_op.drop_column('auto_reply_style')
        batch_op.drop_column('auto_reply_tone')

    # ### end Alembic commands ###
